// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Src.Connection;

#nullable disable

namespace SorteioAPI.Migrations
{
    [DbContext(typeof(SorteioDbContext))]
    [Migration("20231130210742_03_MakeValor_as_ID_From_NumberModel")]
    partial class _03_MakeValor_as_ID_From_NumberModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Src.Pessoa.Models.NumeroModel", b =>
                {
                    b.Property<string>("Valor")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("PessoaEmail")
                        .IsRequired()
                        .HasColumnType("character varying(40)");

                    b.HasKey("Valor");

                    b.HasIndex("PessoaEmail");

                    b.ToTable("Numero");
                });

            modelBuilder.Entity("Src.Pessoa.Models.PessoaModel", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Email");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("Src.Pessoa.Models.NumeroModel", b =>
                {
                    b.HasOne("Src.Pessoa.Models.PessoaModel", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });
#pragma warning restore 612, 618
        }
    }
}
